### ISSUE TITLE
Viewer only works sometimes

### ISSUE THREAD

**Issue by rodrigogomesrc** [TannerGabriel/WebRTC-Video-Broadcast#17]
I was testing your project because I need to create live transmission and I need a starting point. But I've found something weird: most of the times the viewer simply doesn't show anything. I spent hours making some tests and trying to found the cause, and what I found out is that it doesn't show any errors and I haven't found any difference on the communication when comparing the logging of when the viewer works with when it doesn't. But I found out something odd that I'm not sure if it's supposed to work like that and I think maybe it has to do with this issue.

When I try to make the stream the video, that's what happens:

peerConnection.ontrack and peerConnection.onincecandidate functions on watch.js file are executing two times each 

On the broadcast.js file the peerConnection.onicecandidate is executing a variable number of times (usually 3 - 12 times)

And it seens that the problem is getting more frequent the more I test it. Because when I started testing it was working fine, but then it starting getting worse and worse,

Any ideias of what's happening and how can it been fixed?

I'm using Chrome 84.0.4147.89 in Linux Ubuntu

**Comment by MATTiVOLTARii** [comment]
Hi, I have the same issue that most of the times on the viewer site nothing displayed. 
I also spent hours testing and changing the lifecycle. Nothing works. On Localhost viewer works every time. 
I would be very thankful for a fix.

Im not a expert but i guess the multiple executions have something to do with candidate negotiation.

**Comment by TannerGabriel** [comment]
That sounds like very interesting findings. I will check this problem out myself in the coming weeks and try to find a fix.

**Comment by TannerGabriel** [comment]
I have not reproduced your problem yet, but I think the problem could occur if you have not defined a TURN server in your script (This repository only adds a STUN server because they are publicly accessible).

Creating your own TURN server can be done using [Coturn](https://github.com/coturn/coturn) or by running a TURN server example of the [Golang WebRTC pion library](https://github.com/pion/turn/tree/master/examples).

You can then add the TURN server in your script using the following syntax in your config:

```bash
const config = {
  iceServers: [
      { 
        "urls": "stun:stun.l.google.com:19302",
      },
      { 
        "urls": "turn:TURN_IP?transport=tcp",
        "username": "USERNAME",
        "credential": "PASSWORD"
      }
  ]
};
```

I also plan on writing an article about how you can set up and configure your own Turn server. 

I hope this helps, and I will take a look at a closer look at the issue as soon as possible.

**Comment by rajgits** [comment]
Hi, i go through your tutorial it was awesome, mean while i have requirement by using STUN and TURN server even i created and validated its fine, but when i replace with your code(brodcast.js and watch.js ) its not working even though i couldn't find errors also..please if you any idea or suggestion please let me know.

**Comment by TannerGabriel** [comment]
The application currently only supports only one broadcaster, and it will stay that way. Still, I'm planning to also make a WebRTC application that features different chat rooms that you can connect to using some kind of ID or URL like Zoom.
