### ISSUE TITLE
Only a still shot remotely

### ISSUE THREAD

**Issue by TeAmigo** [TannerGabriel/WebRTC-Video-Broadcast#23]
Running the server and connecting as the broadcaster then watching from another browser on the same machine works well. But, when I connect from my phone as a watcher, I only get a still image, not the video. Any ideas why?

**Comment by TannerGabriel** [comment]
If the phone is not on the same network, you will need a TURN server so the signaling process works correctly because the peer connection cannot be established directly. If you don't know how to create a TURN server you can reference [this tutorial](https://gabrieltanner.org/blog/turn-server). Also adding the TURN server to the application is documented in the README.

There could also be an issue with the mobile browser not supporting the WebRTC protocol. 

If this does not help then please provide more information about your setup and if you changed something in the codebase.
