### ISSUE TITLE
Not running on Raspberry Pi

### ISSUE THREAD

**Issue by MakeSenseIoT** [TannerGabriel/WebRTC-Video-Broadcast#33]
**Describe the bug**
When install and run on RPi shows Windows camera

**To Reproduce**
1. Install on RPi
2. replace original server.js with attached server.js
3. run it from a browser on local network 

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - CPU architecture: [e.g. x86]

**Dependency versions:**
 - Nodejs version: [e.g. 10]
[server.zip](https://github.com/TannerGabriel/WebRTC-Video-Broadcast/files/6412750/server.zip)

**Additional context (optional)**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/WebRTC-Video-Broadcast/issues?q=is%3Aissue)

**Comment by MakeSenseIoT** [comment]
![RPi_1](https://user-images.githubusercontent.com/53611049/116839101-4f9dd800-ac14-11eb-9ece-b98b38dd2a4a.jpg)
![RPi_2](https://user-images.githubusercontent.com/53611049/116839107-5298c880-ac14-11eb-9cc1-a5289cb8cb8b.jpg)

**Comment by TannerGabriel** [comment]
Sorry for the late response. I'm not quite sure what your problem here is because the application shows the camera of the device that is accessing the `/broadcast.html` endpoint. That means that no matter if you are hosting the application on a Raspberry Pi the application, will stream your windows camera if you access the `/broadcast.html` endpoint from your windows device.

Hopefully, this helps you solve your problem. If not, let me know and I will take a closer look.

**Comment by MakeSenseIoT** [comment]
thanks for responding. I have a problem with navigator.mediaDevices ( is undefined) Have to figure out how to start drivers for camera and microphone on RPi. 
![WebRTC_RPi](https://user-images.githubusercontent.com/53611049/117806757-16153e80-b29e-11eb-8ca9-7aff5ae38a26.jpg)

**Comment by MakeSenseIoT** [comment]
when I run webrtc example from uv4l site https://www.linux-projects.org/uv4l/tutorials/streaming-server/ my camera and microphone work, but I don't know how to start their drivers outside that example

**Comment by TannerGabriel** [comment]
Yes, that is because you can only access things like `mediaDevices` on localhost when using HTTP. If you want to use them on other domains than localhost, you will need to use HTTPS instead.

Here are some additional readings if you are interested:
- https://blog.mozilla.org/webrtc/camera-microphone-require-https-in-firefox-68/
- https://w3c.github.io/webappsec-secure-contexts/#localhost

**Comment by MakeSenseIoT** [comment]
Thanks again.
Your code work for me on my local network using both http and https.
I use one computer as broadcaster and others including Macbook and iPhone as clients
and all works nice.
On raspberry pi with https I have a funny effect after running https://192.168.0.83:4000/broadcast I have a stream from my PC, not from Raspberry Pi. My guess is that here is something in the broadcast.js code causing the use of IP address of localhost (my desktop PC) instead of IP address of RPi (192.168.0.83).
Can you kindly have a look and help to fix it?
I renamed here server_new.js into server_new.txt as .js is not accepted to be attached

root@raspberrypi:~# cd /www/WebRTC-Video-Broadcast
root@raspberrypi:/www/WebRTC-Video-Broadcast# node server_new.js
Server IP is: 192.168.0.83
Express server listening on:  192.168.0.83 : 4000

![Rpi3](https://user-images.githubusercontent.com/53611049/117906685-c0ca4300-b318-11eb-826f-3405e93a54a4.jpg)
[server_new.txt](https://github.com/TannerGabriel/WebRTC-Video-Broadcast/files/6462911/server_new.txt)
